AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RequestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'translate-request-bucket-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30
      AccelerateConfiguration:
        AccelerationStatus: Enabled

  ResponseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'translate-response-bucket-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30
      AccelerateConfiguration:
        AccelerationStatus: Enabled

  TranslateExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: translate-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranslateS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - translate:TranslateText
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
